.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "MUSTACHE" "5" "September 2022" "DEFUNKT" "Mustache Manual"
.SH "NAME"
\fBmustache\fR \- Logic\-less templates\.
.SH "SYNOPSIS"
A typical Mustache template:
.IP "" 4
.nf
Hello {{name}}
You have just won {{value}} dollars!
{{#in_ca}}
Well, {{taxed_value}} dollars, after taxes\.
{{/in_ca}}
.fi
.IP "" 0
.P
Given the following hash:
.IP "" 4
.nf
{
  "name": "Chris",
  "value": 10000,
  "taxed_value": 10000 \- (10000 * 0\.4),
  "in_ca": true
}
.fi
.IP "" 0
.P
Will produce the following:
.IP "" 4
.nf
Hello Chris
You have just won 10000 dollars!
Well, 6000\.0 dollars, after taxes\.
.fi
.IP "" 0
.SH "DESCRIPTION"
Mustache can be used for HTML, config files, source code \- anything\. It works by expanding tags in a template using values provided in a hash or object\.
.P
We call it "logic\-less" because there are no if statements, else clauses, or for loops\. Instead there are only tags\. Some tags are replaced with a value, some nothing, and others a series of values\. This document explains the different types of Mustache tags\.
.P
The Mustache language has a formal specification \fIhttps://github\.com/mustache/spec\fR\. The current manpage reflects version 1\.3\.0 of the specification, including the official\-but\-optional extensions for lambdas and inheritance\.
.SH "TAG TYPES"
Tags are indicated by the double mustaches\. \fB{{person}}\fR is a tag, as is \fB{{#person}}\fR\. In both examples, we'd refer to \fBperson\fR as the key or tag key\. Let's talk about the different types of tags\.
.SS "Variables"
The most basic tag type is the variable\. A \fB{{name}}\fR tag in a basic template will try to find the \fBname\fR key in the current context\. If there is no \fBname\fR key, the parent contexts will be checked recursively\. If the top context is reached and the \fBname\fR key is still not found, nothing will be rendered\.
.P
All variables are HTML escaped by default\. If you want to return raw contents without escaping, use the triple mustache: \fB{{{name}}}\fR\.
.P
You can also use \fB&\fR to return its raw contents: \fB{{& name}}\fR\. This may be useful when changing delimiters (see "Set Delimiter" below)\.
.P
By default a variable "miss" returns an empty string\. This can usually be configured in your Mustache library\. The Ruby version of Mustache supports raising an exception in this situation, for instance\.
.P
Template:
.IP "" 4
.nf
* {{name}}
* {{age}}
* {{company}}
* {{{company}}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "name": "Chris",
  "company": "<b>GitHub</b>"
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
* Chris
*
* &lt;b&gt;GitHub&lt;/b&gt;
* <b>GitHub</b>
.fi
.IP "" 0
.P
\fBDotted Names\fR
.P
If the \fBname\fR contains dots, it is split on the dots to obtain multiple keys\. The first key is looked up in the context as described above\. If it is found, the next key is looked up within the previous result\. This is repeated until a key is not found or until the last key is found\. The final result is interpolated as above\.
.P
Template:
.IP "" 4
.nf
* {{client\.name}}
* {{age}}
* {{client\.company\.name}}
* {{{company\.name}}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "client": {
    "name": "Chris & Friends",
    "age": 50
  },
  "company": {
    "name": "<b>GitHub</b>"
  }
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
* Chris &amp; Friends
*
*
* <b>GitHub</b>
.fi
.IP "" 0
.P
\fBImplicit Iterator\fR
.P
As a special case, if the \fBname\fR consists of only a dot and nothing else, the value that is the current context is interpolated as a whole\. This is especially useful if the parent context is a list; see \fBSections\fR below\.
.P
Template:
.IP "" 4
.nf
* {{\.}}
.fi
.IP "" 0
.P
Current context:
.IP "" 4
.nf
"Hello!"
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
* Hello!
.fi
.IP "" 0
.P
\fBLambdas\fR
.P
If any value found during the lookup is a callable object, such as a function or lambda, this object will be invoked with zero arguments\. The value that is returned is then used instead of the callable object itself\.
.P
An \fBoptional\fR part of the specification states that if the final key in the \fBname\fR is a lambda that returns a string, then that string should be rendered as a Mustache template before interpolation\. It will be rendered using the default delimiters (see \fBSet Delimiter\fR below) against the current context\.
.P
Template:
.IP "" 4
.nf
* {{time\.hour}}
* {{today}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "year": 1970,
  "month": 1,
  "day": 1,
  "time": function() {
    return {
      "hour": 0,
      "minute": 0,
      "second": 0
    }
  },
  "today": function() {
    return "{{year}}\-{{month}}\-{{day}}"
  }
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
* 0
* 1970\-1\-1
.fi
.IP "" 0
.SS "Sections"
Sections render blocks of text zero or more times, depending on the value of the key in the current context\.
.P
Lookup of dotted names works in the same way as with variables, except for slightly different treatment of lambdas\. More on this below\.
.P
A section begins with a pound and ends with a slash\. That is, \fB{{#person}}\fR begins a "person" section while \fB{{/person}}\fR ends it\.
.P
The behavior of the section is determined by the final value of the key lookup\.
.P
\fBFalse Values or Empty Lists\fR
.P
If the \fBperson\fR key exists and has a value of false or an empty list, the HTML between the pound and slash will not be displayed\.
.P
Template:
.IP "" 4
.nf
Shown\.
{{#person}}
  Never shown!
{{/person}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "person": false
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
Shown\.
.fi
.IP "" 0
.P
\fBNon\-Empty Lists\fR
.P
If the \fBperson\fR key exists and has a non\-false value, the HTML between the pound and slash will be rendered and displayed one or more times\.
.P
When the value is a non\-empty list, the text in the block will be displayed once for each item in the list\. The context of the block will be set to the current item for each iteration\. In this way we can loop over collections\.
.P
Template:
.IP "" 4
.nf
{{#repo}}
  <b>{{name}}</b>
{{/repo}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "repo": [
    { "name": "resque" },
    { "name": "hub" },
    { "name": "rip" }
  ]
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
  <b>resque</b>
  <b>hub</b>
  <b>rip</b>
.fi
.IP "" 0
.P
The same effect as above can be obtained without nested objects, by using the implicit iterator (see \fBVariables\fR above)\.
.P
Template:
.IP "" 4
.nf
{{#repo}}
  <b>{{\.}}</b>
{{/repo}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "repo": ["resque", "hub", "rip"]
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
  <b>resque</b>
  <b>hub</b>
  <b>rip</b>
.fi
.IP "" 0
.P
\fBLambdas\fR
.P
When any value found during the lookup is a callable object, such as a function or lambda, the object will be invoked and passed the block of text\. The text passed is the literal block, unrendered\. \fB{{tags}}\fR will not have been expanded\.
.P
An \fBoptional\fR part of the specification states that if the final key in the \fBname\fR is a lambda that returns a string, then that string replaces the content of the section\. It will be rendered using the same delimiters (see \fBSet Delimiter\fR below) as the original section content\. In this way you can implement filters or caching\.
.P
Template:
.IP "" 4
.nf
{{#wrapped}}{{name}} is awesome\.{{/wrapped}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "name": "Willy",
  "wrapped": function(text) {
    return "<b>" + text + "</b>"
  }
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
<b>Willy is awesome\.</b>
.fi
.IP "" 0
.P
\fBNon\-False Values\fR
.P
When the value is non\-false but not a list, it will be used as the context for a single rendering of the block\.
.P
Template:
.IP "" 4
.nf
{{#person?}}
  Hi {{name}}!
{{/person?}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "person?": { "name": "Jon" }
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
  Hi Jon!
.fi
.IP "" 0
.SS "Inverted Sections"
An inverted section begins with a caret (hat) and ends with a slash\. That is \fB{{^person}}\fR begins a "person" inverted section while \fB{{/person}}\fR ends it\.
.P
While sections can be used to render text zero or more times based on the value of the key, inverted sections may render text once based on the inverse value of the key\. That is, they will be rendered if the key doesn't exist, is false, or is an empty list\.
.P
Template:
.IP "" 4
.nf
{{#repo}}
  <b>{{name}}</b>
{{/repo}}
{{^repo}}
  No repos :(
{{/repo}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "repo": []
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
  No repos :(
.fi
.IP "" 0
.SS "Comments"
Comments begin with a bang and are ignored\. The following template:
.IP "" 4
.nf
<h1>Today{{! ignore me }}\.</h1>
.fi
.IP "" 0
.P
Will render as follows:
.IP "" 4
.nf
<h1>Today\.</h1>
.fi
.IP "" 0
.P
Comments may contain newlines\.
.SS "Partials"
Partials begin with a greater than sign, like \fB{{> box}}\fR\.
.P
Partials are rendered at runtime (as opposed to compile time), so recursive partials are possible\. Just avoid infinite loops\.
.P
They also inherit the calling context\. Whereas in ERB you may have this:
.IP "" 4
.nf
<%= partial :next_more, :start => start, :size => size %>
.fi
.IP "" 0
.P
Mustache requires only this:
.IP "" 4
.nf
{{> next_more}}
.fi
.IP "" 0
.P
Why? Because the \fBnext_more\.mustache\fR file will inherit the \fBsize\fR and \fBstart\fR methods from the calling context\.
.P
In this way you may want to think of partials as includes, or template expansion, even though it's not literally true\.
.P
For example, this template and partial:
.IP "" 4
.nf
base\.mustache:
<h2>Names</h2>
{{#names}}
  {{> user}}
{{/names}}

user\.mustache:
<strong>{{name}}</strong>
.fi
.IP "" 0
.P
Can be thought of as a single, expanded template:
.IP "" 4
.nf
<h2>Names</h2>
{{#names}}
  <strong>{{name}}</strong>
{{/names}}
.fi
.IP "" 0
.P
\fBDynamic Names\fR
.P
Partials can be loaded dynamically at runtime using Dynamic Names; an \fBoptional\fR part of the Mustache specification which allows to dynamically determine a tag's content at runtime\.
.P
Dynamic Names consists of an asterisk, followed by a dotted name which follows the same notation and the same resolution as in an variable tag\. That is \fB{{>*dynamic}}\fR\. It can be thought as the following \fBhypothetical\fR tag (which is \fBnot allowed\fR!): \fB{{>{{dynamic}}}}\fR\.
.P
Templates:
.IP "" 4
.nf
main\.mustache:
Hello {{>*dynamic}}

world\.template:
everyone!
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "dynamic": "world"
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
Hello everyone!
.fi
.IP "" 0
.SS "Blocks"
A block begins with a dollar and ends with a slash\. That is, \fB{{$title}}\fR begins a "title" block and \fB{{/title}}\fR ends it\.
.P
Blocks mark parts of the template that may be overridden\. This can be done with a block of the same name within a parent section in the calling template (see \fBParents\fR below)\. If not overridden, the contents of a block render just as if the \fB{{$title}}\fR and \fB{{/title}}\fR tags weren't there\.
.P
Blocks could be thought of as template parameters or as inline partials that may be passed to another template\. They are part of the optional inheritance extension\.
.P
Template \fBarticle\.mustache\fR:
.IP "" 4
.nf
<h1>{{$title}}The News of Today{{/title}}</h1>
{{$body}}
<p>Nothing special happened\.</p>
{{/body}}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
<h1>The News of Today</h1>
<p>Nothing special happened\.</p>
.fi
.IP "" 0
.SS "Parents"
A parent begins with a less than sign and ends with a slash\. That is, \fB{{<article}}\fR begins an "article" parent and \fB{{/article}}\fR ends it\.
.P
Like an \fB{{>article}}\fR partial, a parent lets you expand another template inside the current one\. Unlike a partial, a parent also lets you override blocks of the other template\.
.P
Blocks within a parent can again be overridden by another including template\. Other content within a parent is ignored, like comments\.
.P
Template:
.IP "" 4
.nf
{{<article}}
  Never shown
  {{$body}}
    {{#headlines}}
    <p>{{\.}}</p>
    {{/headlines}}
  {{/body}}
{{/article}}

{{<article}}
  {{$title}}Yesterday{{/title}}
{{/article}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "headlines": [
    "A pug's handler grew mustaches\.",
    "What an exciting day!"
  ]
}
.fi
.IP "" 0
.P
Output, assuming the \fBarticle\.mustache\fR from before:
.IP "" 4
.nf
<h1>The News of Today</h1>
<p>A pug's handler grew mustaches\.</p>
<p>What an exciting day!</p>

<h1>Yesterday</h1>
<p>Nothing special happened\.</p>
.fi
.IP "" 0
.P
\fBDynamic Names\fR
.P
Some mustache implementations may allow the use of Dynamic Names in parent tags, similar to dynamic names in partials\. Here's an example of how Dynamic Names in parent tags work\.
.P
Templates:
.IP "" 4
.nf
{{!normal\.mustache}}
{{$text}}Here goes nothing\.{{/text}}

{{!bold\.mustache}}
<b>{{$text}}Here also goes nothing but it's bold\.{{/text}}</b>

{{!dynamic\.mustache}}
{{<*dynamic}}
  {{$text}}Hello World!{{/text}}
{{/*dynamic}}
.fi
.IP "" 0
.P
Hash:
.IP "" 4
.nf
{
  "dynamic": "bold"
}
.fi
.IP "" 0
.P
Output:
.IP "" 4
.nf
<b>Hello World!</b>
.fi
.IP "" 0
.SS "Set Delimiter"
Set Delimiter tags start with an equal sign and change the tag delimiters from \fB{{\fR and \fB}}\fR to custom strings\.
.P
Consider the following contrived example:
.IP "" 4
.nf
* {{default_tags}}
{{=<% %>=}}
* <% erb_style_tags %>
<%={{ }}=%>
* {{ default_tags_again }}
.fi
.IP "" 0
.P
Here we have a list with three items\. The first item uses the default tag style, the second uses erb style as defined by the Set Delimiter tag, and the third returns to the default style after yet another Set Delimiter declaration\.
.P
According to ctemplates \fIhttp://goog\-ctemplate\.sourceforge\.net/doc/howto\.html\fR, this "is useful for languages like TeX, where double\-braces may occur in the text and are awkward to use for markup\."
.P
Custom delimiters may not contain whitespace or the equals sign\.
.SH "COPYRIGHT"
Mustache is Copyright (C) 2009 Chris Wanstrath
.P
Original CTemplate by Google
.SH "SEE ALSO"
mustache(1), \fIhttp://mustache\.github\.io/\fR
